# Generated by Django 5.0.7 on 2024-07-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0003_comment_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
